spring.application.name=seguridadcalidad
backend.base-url=${BACKEND_URL:http://localhost:8081}
logging.level.com.duoc.seguridadcalidad=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.http=INFO
logging.file.path=./logs
app.security.jwt-cookie.secure=${JWT_COOKIE_SECURE:true}
app.security.jwt-cookie.max-age-seconds=${JWT_COOKIE_MAX_AGE_SECONDS:3600}
app.security.jwt-cookie.same-site=${JWT_COOKIE_SAME_SITE:Strict}

spring.datasource.url=jdbc:mysql://localhost:3306/veterinarias6?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
